#cleaning Food Balance Data

library(tidyr)
library(reshape2)

faostat <- read.csv("unclean_foodbalance.csv")

foa_stat_colsremoved <- subset(faostat, select = c("Area", "Element", "Item", "Value"))

foa_stat_colsmerged <- foa_stat_colsremoved %>%
  unite("Item", Item:Element, sep = ", ", remove = TRUE)

foa_reshaped <- dcast(foa_stat_colsmerged, Area ~ Item, fill = 0)

colnames(foa_reshaped) <- c("Area",
                           "Alcoholic Beverages, Fat supply quantity",
                           "Alcoholic Beverages, Food supply",
                           "Alcoholic Beverages, Food supply quantity",
                           "Alcoholic Beverages, Protein supply quantity",
                           "Animal fats, Fat supply quantity",
                           "Animal fats, Food supply",
                           "Animal fats, Food supply quantity",
                           "Animal fats, Protein supply quantity",
                           "Animal Products, Fat supply quantity",
                           "Animal Products, Food supply",
                           "Animal Products, Protein supply quantity",
                           "Aquatic Products, Other, Fat supply quantity",
                           "Aquatic Products, Other, Food supply",
                           "Aquatic Products, Other, Food supply quantity",
                           "Aquatic Products, Other, Protein supply quantity",
                           "Cereals - Excluding Beer, Fat supply quantity",
                           "Cereals - Excluding Beer, Food supply",
                           "Cereals - Excluding Beer, Food supply quantity",
                           "Cereals - Excluding Beer, Protein supply quantity",
                           "Eggs, Fat supply quantity",
                           "Eggs, Food supply",
                           "Eggs, Food supply quantity",
                           "Eggs, Protein supply quantity",
                           "Fish, Seafood, Fat supply quantity",
                           "Fish, Seafood, Food supply",
                           "Fish, Seafood, Food supply quantity",
                           "Fish, Seafood, Protein supply quantity",
                           "Fruits - Excluding Wine, Fat supply quantity",
                           "Fruits - Excluding Wine, Food supply",
                           "Fruits - Excluding Wine, Food supply quantity",
                           "Fruits - Excluding Wine, Protein supply quantity",
                           "Grand Total, Fat supply quantity",
                           "Grand Total, Food supply",
                           "Grand Total, Protein supply quantity",
                           "Meat, Fat supply quantity",
                           "Meat, Food supply",
                           "Meat, Food supply quantity",
                           "Meat, Protein supply quantity",
                           "Milk - Excluding Butter, Fat supply quantity",
                           "Milk - Excluding Butter, Food supply",
                           "Milk - Excluding Butter, Food supply quantity",
                           "Milk - Excluding Butter, Protein supply quantity",
                           "Miscellaneous, Fat supply quantity",
                           "Miscellaneous, Food supply",
                           "Miscellaneous, Food supply quantity",
                           "Miscellaneous, Protein supply quantity",
                           "Offals, Fat supply quantity",
                           "Offals, Food supply",
                           "Offals, Food supply quantity",
                           "Offals, Protein supply quantity",
                           "Oilcrops, Fat supply quantity",
                           "Oilcrops, Food supply",
                           "Oilcrops, Food supply quantity",
                           "Oilcrops, Protein supply quantity",
                           "Population, Total Population - Both sexes",
                           "Pulses, Fat supply quantity",
                           "Pulses, Food supply",
                           "Pulses, Food supply quantity",
                           "Pulses, Protein supply quantity",
                           "Spices, Fat supply quantity",
                           "Spices, Food supply",
                           "Spices, Food supply quantity",
                           "Spices, Protein supply quantity",
                           "Starchy Roots, Fat supply quantity",
                           "Starchy Roots, Food supply",
                           "Starchy Roots, Food supply quantity",
                           "Starchy Roots, Protein supply quantity",
                           "Stimulants, Fat supply quantity",
                           "Stimulants, Food supply",
                           "Stimulants, Food supply quantity",
                           "Stimulants, Protein supply quantity",
                           "Sugar & Sweeteners, Fat supply quantity",
                           "Sugar & Sweeteners, Food supply",
                           "Sugar & Sweeteners, Food supply quantity",
                           "Sugar & Sweeteners, Protein supply quantity",
                           "Sugar Crops, Fat supply quantity",
                           "Sugar Crops, Food supply",
                           "Sugar Crops, Food supply quantity",
                           "Sugar Crops, Protein supply quantity",
                           "Treenuts, Fat supply quantity",
                           "Treenuts, Food supply",
                           "Treenuts, Food supply quantity",
                           "Treenuts, Protein supply quantity",
                           "Vegetable Oils, Fat supply quantity",
                           "Vegetable Oils, Food supply",
                           "Vegetable Oils, Food supply quantity",
                           "Vegetable Oils, Protein supply quantity",
                           "Vegetables, Fat supply quantity",
                           "Vegetables, Food supply",
                           "Vegetables, Food supply quantity",
                           "Vegetables, Protein supply quantity",
                           "Vegetal Products, Fat supply quantity",
                           "Vegetal Products, Food supply",
                           "Vegetal Products, Protein supply quantity")
saveRDS(foa_reshaped, "foodbalance.Rds")